### ISSUE TITLE
Proposal: `system.SetEnvironment` actor

### ISSUE THREAD

**Issue by mikhail** [Nextdoor/kingpin#354]
A phony actor that could set environment variable during runtime for the remainder.

``` yaml
actor: system.SetEnvironment
  - options:
    variables:
      AWS_ACCESS_KEY_ID: %PROD_AWS_ACCESS_KEY_ID%
      AWS_SECRET_ACCESS_KEY: %PROD_AWS_SECRET_ACCESS_KEY%
```
