### ISSUE TITLE
Group Actors Fill Context Tokens Before Loading Context

### ISSUE THREAD

**Issue by colinking** [Nextdoor/kingpin#448]
```yaml
# test.yaml
actor: group.Sync
options:
  contexts: "test-context.yaml"
  acts:
    - actor: misc.Note
      options:
        message: "{CONTEXT_VALUE|Default Value}"
```
```yaml
# test-context.yaml
- CONTEXT_VALUE: "Hello World"
```

This outputs `"Default Value"` instead of `"Hello World"`.

It appears that when a group actor is initialized, it will attempt to fill in context tokens _prior to loading any specified context_ as part of the `BaseActor` constructor (which calls `_fill_in_contexts` with the `_init_context`).

This appears to be related to a larger issue, caused by multiple levels of group actors, each with their own context, where tokens are removed too soon (because they aren't defined until later `contexts`). An example (this prints `"Foo Bar"` not `"Hello World"`):

```yaml
# test2.yaml
actor: group.Sync
options:
  contexts: "test-context1.yaml"
  acts:
    - actor: group.Sync
       options:
         contexts: "test-context2.yaml"
         acts:
           - actor: misc.Note
              options:
                message: "{HELLO_TOKEN|Foo} {WORLD_TOKEN|Bar}"
```
```yaml
# test-context1.yaml
- HELLO_TOKEN: "Hello"
```
```yaml
# test-context2.yaml
- WORLD_TOKEN: "World"
```

I'll submit a PR with a potential solution for both. This will change how context tokens are filled. Instead of blindly replacing all context tokens in the options subtree (via converting the JSON to a string), it'll traverse the tree and stop substituting context tokens in any group actors which defines a `contexts` field. The in-progress PR is here: https://github.com/Nextdoor/kingpin/compare/master...colinking:colin/group_contexts
